datasets link: https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
df = df.iloc[:1000]

In [4]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.shape

(1000, 2)

In [6]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [7]:
df['sentiment'].value_counts()

sentiment
positive    501
negative    499
Name: count, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
df.drop_duplicates(inplace=True)

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


Basic Preprocessing

Remove tags

Lowercase

remove stopwords

In [11]:
import re
def remove_tags(raw_text):
    cleaned_text = re.sub(re.compile('<.*?>'),'',raw_text)
    return cleaned_text

In [12]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [13]:
df

review sentiment
0    One of the other reviewers has mentioned that ...  positive
1    A wonderful little production. The filming tec...  positive
2    I thought this was a wonderful way to spend ti...  positive
3    Basically there's a family where a little boy ...  negative
4    Petter Mattei's "Love in the Time of Money" is...  positive
..                                                 ...       ...
995  Nothing is sacred. Just ask Ernie Fosselius. T...  positive
996  I hated it. I hate self-aware pretentious inan...  negative
997  I usually try to be professional and construct...  negative
998  If you like me is going to see this in a film ...  negative
999  This is like a zoology textbook, given that it...  negative

[1000 rows x 2 columns]

In [14]:
df['sentiment'].value_counts()

sentiment
positive    501
negative    499
Name: count, dtype: int64

In [15]:
df['review'] = df['review'].apply(lambda x:x.lower())
df

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\4005667089.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


review sentiment
0    one of the other reviewers has mentioned that ...  positive
1    a wonderful little production. the filming tec...  positive
2    i thought this was a wonderful way to spend ti...  positive
3    basically there's a family where a little boy ...  negative
4    petter mattei's "love in the time of money" is...  positive
..                                                 ...       ...
995  nothing is sacred. just ask ernie fosselius. t...  positive
996  i hated it. i hate self-aware pretentious inan...  negative
997  i usually try to be professional and construct...  negative
998  if you like me is going to see this in a film ...  negative
999  this is like a zoology textbook, given that it...  negative

[1000 rows x 2 columns]

In [16]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\2826946130.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [17]:
df

review sentiment
0    one reviewers mentioned watching 1 oz episode ...  positive
1    wonderful little production. filming technique...  positive
2    thought wonderful way spend time hot summer we...  positive
3    basically there's family little boy (jake) thi...  negative
4    petter mattei's "love time money" visually stu...  positive
..                                                 ...       ...
995  nothing sacred. ask ernie fosselius. days, eve...  positive
996  hated it. hate self-aware pretentious inanity ...  negative
997  usually try professional constructive criticiz...  negative
998  like going see film history class something li...  negative
999  like zoology textbook, given depiction animals...  negative

[1000 rows x 2 columns]

In [18]:
x = df.iloc[:,0:1]
y = df['sentiment']

In [19]:
x

review
0    one reviewers mentioned watching 1 oz episode ...
1    wonderful little production. filming technique...
2    thought wonderful way spend time hot summer we...
3    basically there's family little boy (jake) thi...
4    petter mattei's "love time money" visually stu...
..                                                 ...
995  nothing sacred. ask ernie fosselius. days, eve...
996  hated it. hate self-aware pretentious inanity ...
997  usually try professional constructive criticiz...
998  like going see film history class something li...
999  like zoology textbook, given depiction animals...

[1000 rows x 1 columns]

In [20]:
y

0      positive
1      positive
2      positive
3      negative
4      positive
         ...   
995    positive
996    negative
997    negative
998    negative
999    negative
Name: sentiment, Length: 1000, dtype: object

In [21]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [22]:
y

array([1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,

In [23]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [24]:
x_train.shape

(800, 1)

In [25]:
# applying BoW
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

In [26]:
x_train_bow.shape

(800, 15935)

In [27]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(x_train_bow,y_train)

GaussianNB()

In [28]:
y_pred = gnb.predict(x_test_bow)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix

accuracy_score(y_test,y_pred)

0.555

In [30]:
confusion_matrix(y_test,y_pred)

array([[58, 56],
       [33, 53]], dtype=int64)

In [31]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(x_train_bow,y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.81

In [32]:
cv = CountVectorizer(max_features=3000)

X_train_bow = cv.fit_transform(x_train['review']).toarray()
X_test_bow = cv.transform(x_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.795

In [33]:
cv = CountVectorizer(ngram_range=(1,2))

x_train_bow = cv.fit_transform(x_train['review']).toarray()
x_test_bow = cv.transform(x_test['review']).toarray()

rf = RandomForestClassifier()

rf.fit(x_train_bow,y_train)
y_pred = rf.predict(x_test_bow)
accuracy_score(y_test,y_pred)

0.74

__Using Tfidf__

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

x_train_tfidf = tfidf.fit_transform(x_train['review']).toarray()
x_test_tfidf = tfidf.transform(x_test['review'])

In [35]:
rf = RandomForestClassifier()

rf.fit(x_train_tfidf,y_train)
y_pred = rf.predict(x_test_tfidf)

accuracy_score(y_test,y_pred)

0.83

__apply wordtovec__

In [36]:
import numpy as np
import pandas as pd

In [37]:
df = pd.read_csv("IMDB Dataset.csv")
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [38]:
df = df.iloc[:10000]
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[10000 rows x 2 columns]

In [39]:
df.drop_duplicates(inplace=True)

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\3006716147.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [40]:
import re
def remove_tags(raw_test):
    cleaned_text = re.sub(re.compile('<.*?>'),'',raw_test)
    return cleaned_text

In [41]:
df['review'] = df['review'].apply(remove_tags)

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\2336150696.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_tags)


In [42]:
df['review'] = df['review'].apply(lambda x:x.lower())

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\740760900.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x:x.lower())


In [43]:
from nltk.corpus import stopwords

sw_list = stopwords.words('english')

df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

C:\Users\emon1\AppData\Local\Temp\ipykernel_4860\2826946130.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [44]:
df['review']

0       one reviewers mentioned watching 1 oz episode ...
1       wonderful little production. filming technique...
2       thought wonderful way spend time hot summer we...
3       basically there's family little boy (jake) thi...
4       petter mattei's "love time money" visually stu...
                              ...                        
9995    fun, entertaining movie wwii german spy (julie...
9996    give break. anyone say "good hockey movie"? kn...
9997    movie bad movie. watching endless series bad h...
9998    movie probably made entertain middle school, e...
9999    smashing film film-making. shows intense stran...
Name: review, Length: 9983, dtype: object

In [45]:
import gensim

In [46]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [47]:
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [48]:
model = gensim.models.Word2Vec(
    window=10,
    min_count=2
)

In [49]:
model.build_vocab(story)

In [50]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(5875506, 6212140)

In [51]:
len(model.wv.index_to_key)

31845

In [52]:
def document_vector(doc):
    # remove out_of_vocabulary words
        doc = [word for word in doc.split() if word in model.wv.index_to_key]
        return np.mean(model.wv[doc],axis=0)

In [53]:
document_vector(df['review'].values[0])

array([-0.17390278,  0.51328975,  0.21311688,  0.2392325 , -0.10598774,
       -0.5758673 ,  0.21965598,  0.87506515, -0.34437513, -0.29860234,
       -0.26848873, -0.4013526 ,  0.09370172,  0.0963635 ,  0.25295886,
       -0.13724743,  0.01890084, -0.3316821 , -0.04030766, -0.6178103 ,
        0.03240285,  0.2826348 ,  0.05895701, -0.29630595, -0.3751628 ,
        0.00274062, -0.29372954,  0.04185767, -0.30341604,  0.11624324,
        0.32867107,  0.03179754,  0.2327238 , -0.26797128, -0.20704614,
        0.43273038,  0.08130321, -0.2784193 , -0.25311354, -0.79322505,
        0.16255109, -0.20283088,  0.04246888, -0.14972076,  0.46618822,
       -0.10958346, -0.24299078, -0.03204258,  0.06648212,  0.35541263,
        0.03007684, -0.38208532, -0.44562846, -0.14869557, -0.09159174,
        0.23608415,  0.18705489,  0.02428465, -0.27635032,  0.09166355,
        0.01115404,  0.09950858,  0.0314051 , -0.04529102, -0.4169886 ,
        0.27810553,  0.00576143,  0.16823956, -0.36524162,  0.35

In [54]:
from tqdm import tqdm

x = []
for doc in tqdm(df['review'].values):
    x.append(document_vector(doc))

100%|██████████| 9983/9983 [13:09<00:00, 12.65it/s]


In [55]:
x = np.array(x)

In [56]:
x[0]

array([-0.17390278,  0.51328975,  0.21311688,  0.2392325 , -0.10598774,
       -0.5758673 ,  0.21965598,  0.87506515, -0.34437513, -0.29860234,
       -0.26848873, -0.4013526 ,  0.09370172,  0.0963635 ,  0.25295886,
       -0.13724743,  0.01890084, -0.3316821 , -0.04030766, -0.6178103 ,
        0.03240285,  0.2826348 ,  0.05895701, -0.29630595, -0.3751628 ,
        0.00274062, -0.29372954,  0.04185767, -0.30341604,  0.11624324,
        0.32867107,  0.03179754,  0.2327238 , -0.26797128, -0.20704614,
        0.43273038,  0.08130321, -0.2784193 , -0.25311354, -0.79322505,
        0.16255109, -0.20283088,  0.04246888, -0.14972076,  0.46618822,
       -0.10958346, -0.24299078, -0.03204258,  0.06648212,  0.35541263,
        0.03007684, -0.38208532, -0.44562846, -0.14869557, -0.09159174,
        0.23608415,  0.18705489,  0.02428465, -0.27635032,  0.09166355,
        0.01115404,  0.09950858,  0.0314051 , -0.04529102, -0.4169886 ,
        0.27810553,  0.00576143,  0.16823956, -0.36524162,  0.35

In [57]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])

In [58]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [59]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)

In [60]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [61]:
mnb = GaussianNB()
mnb.fit(x_train,y_train)
y_pred = mnb.predict(x_test)
accuracy_score(y_test,y_pred)

0.7215823735603405

In [62]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred = rf.predict(x_test)
accuracy_score(y_test,y_pred)

0.7656484727090636