Word Embedding Techniques using Embedding Layer in Keras

In [1]:
from tensorflow import keras
from keras.preprocessing.text import one_hot

In [2]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
type(sent)

list

In [5]:
# vocab size
voc_size = 500

One Hot Represntation

In [6]:
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[132, 205, 320, 41], [132, 205, 320, 378], [132, 478, 320, 469], [344, 453, 230, 25, 183], [344, 453, 230, 25, 290], [129, 132, 340, 320, 269], [90, 91, 282, 25]]


Word Embedding Represntaion

In [7]:
from tensorflow import keras
from keras.layers import Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)

In [9]:
print(embedded_docs)

[[  0   0   0   0 132 205 320  41]
 [  0   0   0   0 132 205 320 378]
 [  0   0   0   0 132 478 320 469]
 [  0   0   0 344 453 230  25 183]
 [  0   0   0 344 453 230  25 290]
 [  0   0   0 129 132 340 320 269]
 [  0   0   0   0  90  91 282  25]]


In [10]:
dim = 10

model = Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [11]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 493ms/step
[[[ 0.03604424  0.04613736  0.01728849 -0.00801084 -0.0058714
   -0.0422208  -0.04015088 -0.02078236  0.04727241 -0.00368841]
  [ 0.03604424  0.04613736  0.01728849 -0.00801084 -0.0058714
   -0.0422208  -0.04015088 -0.02078236  0.04727241 -0.00368841]
  [ 0.03604424  0.04613736  0.01728849 -0.00801084 -0.0058714
   -0.0422208  -0.04015088 -0.02078236  0.04727241 -0.00368841]
  [ 0.03604424  0.04613736  0.01728849 -0.00801084 -0.0058714
   -0.0422208  -0.04015088 -0.02078236  0.04727241 -0.00368841]
  [ 0.00984702  0.01933748 -0.04390096  0.03279686 -0.03992809
    0.02278491 -0.02397304 -0.01900581 -0.02170166  0.04353413]
  [-0.00298954  0.01236997 -0.03733585 -0.00987739  0.0482314
   -0.04918383 -0.01104261  0.01620415 -0.0144471  -0.00764123]
  [-0.03208139  0.04890471 -0.0466448   0.03492333 -0.02681169
   -0.01979543  0.04992572  0.03648838  0.015409    0.04071606]
  [-0.02828388 -0.00909553  0.03102658 -0.02764823  0.02796972


In [12]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 38ms/step


array([[ 0.03604424,  0.04613736,  0.01728849, -0.00801084, -0.0058714 ,
        -0.0422208 , -0.04015088, -0.02078236,  0.04727241, -0.00368841],
       [ 0.03604424,  0.04613736,  0.01728849, -0.00801084, -0.0058714 ,
        -0.0422208 , -0.04015088, -0.02078236,  0.04727241, -0.00368841],
       [ 0.03604424,  0.04613736,  0.01728849, -0.00801084, -0.0058714 ,
        -0.0422208 , -0.04015088, -0.02078236,  0.04727241, -0.00368841],
       [ 0.03604424,  0.04613736,  0.01728849, -0.00801084, -0.0058714 ,
        -0.0422208 , -0.04015088, -0.02078236,  0.04727241, -0.00368841],
       [ 0.00984702,  0.01933748, -0.04390096,  0.03279686, -0.03992809,
         0.02278491, -0.02397304, -0.01900581, -0.02170166,  0.04353413],
       [-0.00298954,  0.01236997, -0.03733585, -0.00987739,  0.0482314 ,
        -0.04918383, -0.01104261,  0.01620415, -0.0144471 , -0.00764123],
       [-0.03208139,  0.04890471, -0.0466448 ,  0.03492333, -0.02681169,
        -0.01979543,  0.04992572,  0.03648838

In [13]:
embedded_docs[0]

array([  0,   0,   0,   0, 132, 205, 320,  41])