Word Embeddings

In [24]:
import numpy as np
import pandas as pd

In [25]:
df = pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [26]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

In [28]:
bow = cv.fit_transform(df['text'])

In [29]:
# vocab
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [30]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [31]:
cv.transform(['campusx watch and write comment of campusx']).toarray()

array([[2, 1, 0, 1, 1]], dtype=int64)

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(1,2))

In [33]:
bow = cv.fit_transform(df['text'])

In [34]:
# vocab
print(cv.vocabulary_)

{'people': 4, 'watch': 7, 'campusx': 0, 'people watch': 5, 'watch campusx': 8, 'campusx watch': 1, 'write': 9, 'comment': 3, 'people write': 6, 'write comment': 10, 'campusx write': 2}


In [35]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(3,3))

In [36]:
bow = cv.fit_transform(df['text'])

In [37]:
# vocab
print(cv.vocabulary_)

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}


In [38]:
print(len(cv.vocabulary_))

4
