In [2]:
# importing datasets
import pandas as pd

message = pd.read_csv('SMSSpamCollection', sep='\t',names=["label", "message"])

In [3]:
message

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [4]:
message.shape

(5572, 2)

In [5]:
message['message'].loc[100]

"Please don't text me anymore. I have nothing else to say."

In [6]:
# data cleaning and preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\emon1\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [7]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [8]:
corpus = []
for i in range(0,len(message)):
    review = re.sub('[^a-zA-Z]',' ',message['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [10]:
# creating the bag of words model
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=2500,binary=True,ngram_range=(2,2))
x = cv.fit_transform(corpus).toarray()

In [11]:
x[1]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [12]:
x.shape

(5572, 2500)

In [14]:
y = pd.get_dummies(message['label'])
y = y.iloc[:,1].values

In [15]:
# train test split
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=0)

In [16]:
x_train,y_train

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64),
 array([False, False, False, ...,  True, False, False]))

In [ ]:
# creating the bag of words model
# from sklearn.feature_extraction.text import CountVectorizer

# cv = CountVectorizer(max_features=2500,binary=True,ngram_range=(2,2))
# x = cv.fit_transform(corpus).toarray()

In [17]:
from sklearn.naive_bayes import MultinomialNB

spam_detect_model = MultinomialNB().fit(x_train,y_train)
y_pred = spam_detect_model.predict(x_test)

In [18]:
# prediction
y_pred = spam_detect_model.predict(x_test)

In [19]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

score = accuracy_score(y_test,y_pred)

In [20]:
score

0.9730941704035875

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.97      1.00      0.98       955
        True       1.00      0.81      0.90       160

    accuracy                           0.97      1115
   macro avg       0.98      0.91      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [24]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [25]:
y_pred = classifier.predict(x_test)

In [26]:
print(accuracy_score(y_test,y_pred))

0.9704035874439462


In [27]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       False       0.97      1.00      0.98       955
        True       0.98      0.81      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.90      0.93      1115
weighted avg       0.97      0.97      0.97      1115



## Word2Vec implementation

In [28]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

MemoryError: Unable to allocate 3.35 GiB for an array with shape (3000000, 300) and data type float32

In [30]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

In [31]:
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['message'][i])  # Replacing non-alphabetic characters with space
    review = review.lower()  # Converting to lowercase
    review = review.split()  # Splitting into words
    # Applying stemming and filtering out stopwords
    review = [stemmer.stem(word) for word in review if not word in set(stopwords.words('english'))]
    corpus.append(' '.join(review))  # Joining back to form the sentence

In [35]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [33]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess 

In [36]:
corpus[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [37]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for word in simple_preprocess(sent):
        for sent in sent_token:
            words.append(simple_preprocess(sent))

In [38]:
words

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amor',
  

In [39]:
import gensim

In [40]:
# lets tarin word2vec mode

w2v_model = gensim.models.Word2Vec(words,window=5,min_count=2)

In [41]:
w2v_model.wv.index_to_key

['call',
 'ur',
 'gt',
 'lt',
 'get',
 'go',
 'free',
 'day',
 'love',
 'txt',
 'know',
 'like',
 'text',
 'want',
 'time',
 'come',
 'good',
 'send',
 'got',
 'repli',
 'stop',
 'need',
 'mobil',
 'happi',
 'one',
 'ok',
 'today',
 'week',
 'make',
 'co',
 'msg',
 'take',
 'tell',
 'see',
 'think',
 'say',
 'hope',
 'new',
 'back',
 'give',
 'www',
 'miss',
 'phone',
 'min',
 'thing',
 'dont',
 'tone',
 'amp',
 'pleas',
 'claim',
 'friend',
 'pl',
 'ask',
 'hi',
 'even',
 'lor',
 'night',
 'still',
 'everi',
 'home',
 'work',
 'life',
 'win',
 'uk',
 'would',
 'sorri',
 'nokia',
 'tri',
 'much',
 'wait',
 'said',
 'feel',
 'dear',
 'great',
 'da',
 'number',
 'prize',
 'messag',
 'meet',
 'let',
 'com',
 'cash',
 'end',
 'well',
 'start',
 'smile',
 'keep',
 'went',
 'im',
 'morn',
 'hey',
 'wish',
 'way',
 'thank',
 'care',
 'last',
 'find',
 'wat',
 'girl',
 'gud',
 'realli',
 'later',
 'name',
 'contact',
 'person',
 'urgent',
 'babe',
 'servic',
 'box',
 'year',
 'tomorrow',
 'ye'

In [42]:
w2v_model.corpus_count

47732

In [44]:
w2v_model.wv.most_similar('call')

[('datebox', 0.5237042903900146),
 ('famou', 0.5229513645172119),
 ('nnfwfli', 0.5226697325706482),
 ('deliveri', 0.5091729164123535),
 ('essexcm', 0.5012292861938477),
 ('cal', 0.5009851455688477),
 ('fromm', 0.49992698431015015),
 ('unabl', 0.49288493394851685),
 ('standard', 0.4855806529521942),
 ('landlin', 0.48517221212387085)]

In [47]:
w2v_model.wv.similar_by_word('joy')

[('mandan', 0.7794568538665771),
 ('father', 0.773797869682312),
 ('lifei', 0.7384425401687622),
 ('chore', 0.7261961698532104),
 ('john', 0.7252137064933777),
 ('musthu', 0.7024878263473511),
 ('becz', 0.657974123954773),
 ('jerri', 0.6516434550285339),
 ('undrstndng', 0.6493906378746033),
 ('neces', 0.6490909457206726)]

In [48]:
import numpy as np

In [56]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([w2v_model.wv[word] for word in doc if word in w2v_model.wv.index_to_key],axis=0) #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [57]:
from tqdm import tqdm

In [58]:
words[73]

array([ 0.35663036,  0.50269294, -0.25543022,  0.8085013 ,  0.09707741,
       -0.22963335, -0.43694535,  0.11653844, -0.904064  ,  0.94875306,
        0.13162304,  0.8997583 , -0.30419198, -0.0723493 ,  0.93359524,
        0.74046266, -0.45056906, -0.26777068, -0.88977295, -0.28108242,
       -0.30261856,  0.27770537, -0.03424519,  0.09476458, -0.20785932,
       -0.99048054,  0.15659568, -0.89042526,  0.31566885,  0.06479413,
        0.15819785, -0.08299797,  0.8481171 , -0.7530549 ,  0.06085421,
        0.20528145, -0.76470417, -0.22373669, -0.13023847, -0.4971508 ,
        0.06856984,  0.2812317 , -0.17591612,  0.1629472 , -0.17368008,
        0.2861723 ,  0.63632137, -0.0088938 ,  0.56083316,  0.4157268 ,
        0.50435   , -0.2993771 ,  0.32961792, -0.04756093, -0.3238734 ,
       -0.4547719 , -0.79893214,  0.0131743 , -0.54032314, -0.07603043,
        0.25827178,  1.0247016 ,  0.17179924, -0.0611322 , -0.16744135,
        0.05433683,  0.6242979 ,  0.95120597, -0.6474009 ,  0.37

In [59]:
type(w2v_model.wv.index_to_key)

list